from __future__ import annotations

import unittest
from pathlib import Path

import hologram.context as context_module
from hologram.context import (
    AGENT_PATHS,
    CONTEXT_END,
    CONTEXT_START,
    LEGACY_END,
    LEGACY_START,
    ContextStatus,
    ManagedBlockError,
    inspect_managed_block,
    render_managed_block,
    replace_managed_block,
)


def _legacy_block(
    payload: bytes = b"legacy map\n",
    *,
    line_ending: bytes = b"\n",
) -> bytes:
    return LEGACY_START + line_ending + payload + LEGACY_END + line_ending


def _malformed_contexts() -> dict[str, bytes]:
    canonical = CONTEXT_START + b"\nmap\n" + CONTEXT_END + b"\n"
    legacy = _legacy_block()
    return {
        "canonical-start-only": CONTEXT_START + b"\n",
        "canonical-end-only": CONTEXT_END + b"\n",
        "legacy-start-only": LEGACY_START + b"\n",
        "legacy-end-only": LEGACY_END + b"\n",
        "canonical-reversed": CONTEXT_END + b"\n" + CONTEXT_START + b"\n",
        "legacy-reversed": LEGACY_END + b"\n" + LEGACY_START + b"\n",
        "canonical-repeated-pair": canonical + canonical,
        "legacy-repeated-pair": legacy + legacy,
        "canonical-repeated-start": (
            CONTEXT_START + b"\n" + CONTEXT_START + b"\n" + CONTEXT_END + b"\n"
        ),
        "canonical-repeated-end": (
            CONTEXT_START + b"\n" + CONTEXT_END + b"\n" + CONTEXT_END + b"\n"
        ),
        "legacy-repeated-start": (
            LEGACY_START + b"\n" + LEGACY_START + b"\n" + LEGACY_END + b"\n"
        ),
        "legacy-repeated-end": (
            LEGACY_START + b"\n" + LEGACY_END + b"\n" + LEGACY_END + b"\n"
        ),
        "mixed-pairs": canonical + legacy,
        "mixed-opposite-pairs": legacy + canonical,
        "mixed-half-pair": CONTEXT_START + b"\n" + LEGACY_END + b"\n",
        "nested-legacy-in-canonical": (
            CONTEXT_START
            + b"\n"
            + LEGACY_START
            + b"\n"
            + LEGACY_END
            + b"\n"
            + CONTEXT_END
            + b"\n"
        ),
        "nested-canonical-in-legacy": (
            LEGACY_START
            + b"\n"
            + CONTEXT_START
            + b"\n"
            + CONTEXT_END
            + b"\n"
            + LEGACY_END
            + b"\n"
        ),
    }


class _DecodeBomb(bytes):
    def decode(self, *args: object, **kwargs: object) -> str:
        raise AssertionError("authored bytes must never be decoded")


class ManagedBlockTest(unittest.TestCase):
    def test_exact_constants_api_enum_and_error_contract(self) -> None:
        self.assertEqual(
            AGENT_PATHS,
            {
                "claude": Path("CLAUDE.md"),
                "codex": Path("AGENTS.md"),
                "gemini": Path("GEMINI.md"),
            },
        )
        self.assertEqual(
            (CONTEXT_START, CONTEXT_END),
            (
                b"<!-- hologram:v2:start -->",
                b"<!-- hologram:v2:end -->",
            ),
        )
        self.assertEqual(
            (LEGACY_START, LEGACY_END),
            (
                (
                    b"<!-- hologram:start \xe2\x80\x94 generated, do not edit; "
                    b"refreshed by git hooks -->"
                ),
                b"<!-- hologram:end -->",
            ),
        )
        self.assertEqual(
            tuple((status.name, status.value) for status in ContextStatus),
            (
                ("FRESH", "fresh"),
                ("MISSING", "missing"),
                ("STALE", "stale"),
                ("MALFORMED", "malformed"),
            ),
        )
        self.assertTrue(issubclass(ContextStatus, str))
        self.assertTrue(issubclass(ManagedBlockError, ValueError))
        with self.assertRaises(AttributeError):
            ContextStatus.FRESH.value = "changed"  # type: ignore[misc]
        self.assertEqual(
            context_module.__all__,
            [
                "AGENT_PATHS",
                "CONTEXT_END",
                "CONTEXT_START",
                "LEGACY_END",
                "LEGACY_START",
                "ContextStatus",
                "ManagedBlockError",
                "inspect_managed_block",
                "render_managed_block",
                "replace_managed_block",
            ],
        )

    def test_rendered_block_and_all_agent_payloads_are_exact(self) -> None:
        rendered_map = "# hologram:2 state=" + "a" * 64 + " · regen: hologram build\n"
        block = render_managed_block(rendered_map)
        expected = (
            CONTEXT_START
            + b"\n"
            + b"## Project map (generated by Hologram)\n\n"
            + b"Use this complete map for orientation, placement, reuse, and review. "
            + b"Read source bodies before changing behavior.\n\n"
            + b"```text\n"
            + rendered_map.encode("utf-8")
            + b"```\n"
            + b"Regenerate with: `hologram build`\n"
            + CONTEXT_END
            + b"\n"
        )
        self.assertEqual(block, expected)
        self.assertEqual(
            {agent: block for agent in AGENT_PATHS},
            {
                "claude": expected,
                "codex": expected,
                "gemini": expected,
            },
        )

    def test_refresh_preserves_arbitrary_authored_bytes_exactly(self) -> None:
        prefix = b"\xff# Rules\r\nUse tabs.\r\n\r\n"
        suffix = b"\x80Authored suffix\r\n"
        old_block = render_managed_block("old\n")
        expected = render_managed_block("new \u2192 map\n")
        for line_ending, stale_block in (
            ("lf", old_block),
            ("crlf", old_block.replace(b"\n", b"\r\n")),
        ):
            with self.subTest(line_ending=line_ending):
                existing = prefix + stale_block + suffix
                self.assertEqual(
                    inspect_managed_block(existing, expected),
                    ContextStatus.STALE,
                )
                updated = replace_managed_block(existing, expected)
                self.assertEqual(updated, prefix + expected + suffix)
                self.assertEqual(updated[: len(prefix)], prefix)
                self.assertEqual(updated[-len(suffix) :], suffix)
                self.assertEqual(
                    inspect_managed_block(updated, expected),
                    ContextStatus.FRESH,
                )

    def test_fresh_block_is_idempotent_and_preserves_identity(self) -> None:
        expected = render_managed_block("map\n")
        existing = b"authored\r\n" + expected + b"tail\xff"

        self.assertEqual(inspect_managed_block(existing, expected), ContextStatus.FRESH)
        self.assertIs(replace_managed_block(existing, expected), existing)

    def test_legacy_lf_and_crlf_pairs_are_stale_and_migrate_exactly(self) -> None:
        expected = render_managed_block("new\n")
        for line_ending in (b"\n", b"\r\n"):
            with self.subTest(line_ending=line_ending):
                prefix = b"\xffbefore\r\n"
                suffix = b"after\x80\r\n"
                existing = prefix + _legacy_block(line_ending=line_ending) + suffix
                self.assertEqual(
                    inspect_managed_block(existing, expected),
                    ContextStatus.STALE,
                )
                self.assertEqual(
                    replace_managed_block(existing, expected),
                    prefix + expected + suffix,
                )

    def test_missing_block_appends_only_the_needed_lf(self) -> None:
        expected = render_managed_block("map\n")
        cases = {
            "empty": (b"", b"" + expected),
            "unterminated": (b"rules", b"rules\n" + expected),
            "lf": (b"rules\n", b"rules\n" + expected),
            "crlf": (b"rules\r\n", b"rules\r\n" + expected),
            "bare-cr": (b"rules\r", b"rules\r" + expected),
            "two-lf": (b"rules\n\n", b"rules\n\n" + expected),
            "invalid-utf8": (b"rules\xff", b"rules\xff\n" + expected),
        }
        for name, (existing, wanted) in cases.items():
            with self.subTest(name=name):
                self.assertEqual(
                    inspect_managed_block(existing, expected),
                    ContextStatus.MISSING,
                )
                self.assertEqual(replace_managed_block(existing, expected), wanted)

    def test_inline_marker_text_is_authored_content_not_a_pair(self) -> None:
        expected = render_managed_block("map\n")
        inline = (
            b"Discuss "
            + CONTEXT_START
            + b" and "
            + CONTEXT_END
            + b" here.\r\n"
            + b"prefix "
            + LEGACY_START
            + b" suffix\n"
            + b"`"
            + LEGACY_END
            + b"`\n"
        )
        self.assertEqual(inspect_managed_block(inline, expected), ContextStatus.MISSING)
        self.assertEqual(replace_managed_block(inline, expected), inline + expected)

    def test_duplicate_reversed_unbalanced_mixed_and_nested_are_malformed(
        self,
    ) -> None:
        expected = render_managed_block("expected\n")
        for name, existing in _malformed_contexts().items():
            with self.subTest(name=name):
                self.assertEqual(
                    inspect_managed_block(existing, expected),
                    ContextStatus.MALFORMED,
                )
                with self.assertRaises(ManagedBlockError):
                    replace_managed_block(existing, expected)

    def test_malformed_existing_precedes_invalid_expected(self) -> None:
        for name, existing in _malformed_contexts().items():
            with self.subTest(name=name):
                self.assertEqual(
                    inspect_managed_block(existing, b"expected"),
                    ContextStatus.MALFORMED,
                )
                with self.assertRaisesRegex(ManagedBlockError, "existing context"):
                    replace_managed_block(existing, b"expected")

    def test_expected_must_be_one_complete_canonical_block(self) -> None:
        valid_existing = render_managed_block("old\n")
        invalid_expected = {
            "plain": b"expected",
            "legacy": _legacy_block(),
            "prefix": b"authored\n" + render_managed_block("map\n"),
            "suffix": render_managed_block("map\n") + b"authored",
            "missing-end": CONTEXT_START + b"\nmap\n",
            "duplicate": (
                render_managed_block("one\n") + render_managed_block("two\n")
            ),
            "inline": b"prefix " + CONTEXT_START + b"\n" + CONTEXT_END + b"\n",
        }
        for name, expected in invalid_expected.items():
            with self.subTest(name=name):
                with self.assertRaises(ManagedBlockError):
                    inspect_managed_block(valid_existing, expected)
                with self.assertRaises(ManagedBlockError):
                    replace_managed_block(valid_existing, expected)

    def test_authored_bytes_are_never_decoded(self) -> None:
        expected = render_managed_block("map \u2192 \u03b1\n")
        prefix = b"\xff\xfe\x80rules\r\n"
        suffix = b"\x81tail\r\n"
        existing = _DecodeBomb(prefix + render_managed_block("old\n") + suffix)

        self.assertEqual(
            inspect_managed_block(existing, expected),
            ContextStatus.STALE,
        )
        self.assertEqual(
            replace_managed_block(existing, expected),
            prefix + expected + suffix,
        )

    def test_wrong_input_types_are_rejected_without_coercion(self) -> None:
        expected = render_managed_block("map\n")
        for rendered_map in (b"map\n", bytearray(b"map\n"), None, 1):
            with self.subTest(rendered_map=rendered_map), self.assertRaises(TypeError):
                render_managed_block(rendered_map)  # type: ignore[arg-type]

        for function in (inspect_managed_block, replace_managed_block):
            for existing in ("text", bytearray(), memoryview(b""), None):
                with (
                    self.subTest(function=function.__name__, existing=existing),
                    self.assertRaises(TypeError),
                ):
                    function(existing, expected)  # type: ignore[arg-type]
            for malformed_expected in (
                "text",
                bytearray(expected),
                memoryview(expected),
                None,
            ):
                with (
                    self.subTest(
                        function=function.__name__,
                        expected=malformed_expected,
                    ),
                    self.assertRaises(TypeError),
                ):
                    function(b"", malformed_expected)  # type: ignore[arg-type]


if __name__ == "__main__":
    unittest.main()
