from . import legacy as _legacy
from .legacy import (
    Symbol,
    build_digest,
    embed_digest,
    extract_file,
    has_parser,
    render_simple,
    run_cli,
    scan_files,
)
from .model import (
    Binding,
    BodyEvent,
    BodyEventKind,
    BodyIR,
    CallKind,
    CallRef,
    Diagnostic,
    DiagnosticSeverity,
    FileIR,
    ImportRef,
    Language,
    ProjectIR,
    ReferenceConfidence,
    ReferenceContext,
    ReferenceKind,
    ReferenceRef,
    SourceFile,
    SourceRole,
    SourceSpan,
    Symbol as CanonicalSymbol,
    SymbolId,
    SymbolKind,
    Visibility,
)

__all__ = [
    "Symbol",
    "build_digest",
    "embed_digest",
    "extract_file",
    "has_parser",
    "render_simple",
    "run_cli",
    "scan_files",
    "Binding",
    "BodyEvent",
    "BodyEventKind",
    "BodyIR",
    "CallKind",
    "CallRef",
    "CanonicalSymbol",
    "Diagnostic",
    "DiagnosticSeverity",
    "FileIR",
    "ImportRef",
    "Language",
    "ProjectIR",
    "ReferenceConfidence",
    "ReferenceContext",
    "ReferenceKind",
    "ReferenceRef",
    "SourceFile",
    "SourceRole",
    "SourceSpan",
    "SymbolId",
    "SymbolKind",
    "Visibility",
]


def __getattr__(name: str):
    """Temporarily expose legacy module attributes for v1 compatibility."""
    return getattr(_legacy, name)
