from __future__ import annotations

from enum import StrEnum
from pathlib import Path

CONTEXT_START = b"<!-- hologram:v2:start -->"
CONTEXT_END = b"<!-- hologram:v2:end -->"
LEGACY_START = (
    b"<!-- hologram:start \xe2\x80\x94 generated, do not edit; "
    b"refreshed by git hooks -->"
)
LEGACY_END = b"<!-- hologram:end -->"

AGENT_PATHS = {
    "claude": Path("CLAUDE.md"),
    "codex": Path("AGENTS.md"),
    "gemini": Path("GEMINI.md"),
}


class ContextStatus(StrEnum):
    FRESH = "fresh"
    MISSING = "missing"
    STALE = "stale"
    MALFORMED = "malformed"


class ManagedBlockError(ValueError):
    pass


_MARKERS = (CONTEXT_START, CONTEXT_END, LEGACY_START, LEGACY_END)


def _require_bytes(value: object, name: str) -> bytes:
    if not isinstance(value, bytes):
        raise TypeError(f"{name} must be bytes")
    return value


def _marker_lines(value: bytes) -> dict[bytes, list[tuple[int, int]]]:
    found: dict[bytes, list[tuple[int, int]]] = {marker: [] for marker in _MARKERS}
    start = 0
    while True:
        newline = value.find(b"\n", start)
        if newline < 0:
            content_end = len(value)
            physical_end = len(value)
        else:
            content_end = newline
            if content_end > start and value[content_end - 1] == 0x0D:
                content_end -= 1
            physical_end = newline + 1

        line = value[start:content_end]
        if line in found:
            found[line].append((start, physical_end))

        if newline < 0:
            return found
        start = physical_end


def _managed_range(
    value: bytes,
) -> tuple[ContextStatus, str | None, int | None, int | None]:
    found = _marker_lines(value)
    canonical_starts = found[CONTEXT_START]
    canonical_ends = found[CONTEXT_END]
    legacy_starts = found[LEGACY_START]
    legacy_ends = found[LEGACY_END]
    marker_count = sum(len(positions) for positions in found.values())
    if marker_count == 0:
        return ContextStatus.MISSING, None, None, None

    if (
        len(canonical_starts) == 1
        and len(canonical_ends) == 1
        and not legacy_starts
        and not legacy_ends
    ):
        start = canonical_starts[0][0]
        end = canonical_ends[0][1]
        if start < canonical_ends[0][0]:
            return ContextStatus.STALE, "canonical", start, end
        return ContextStatus.MALFORMED, None, None, None

    if (
        len(legacy_starts) == 1
        and len(legacy_ends) == 1
        and not canonical_starts
        and not canonical_ends
    ):
        start = legacy_starts[0][0]
        end = legacy_ends[0][1]
        if start < legacy_ends[0][0]:
            return ContextStatus.STALE, "legacy", start, end
        return ContextStatus.MALFORMED, None, None, None

    return ContextStatus.MALFORMED, None, None, None


def _validated_expected(expected: object) -> bytes:
    block = _require_bytes(expected, "expected")
    status, kind, start, end = _managed_range(block)
    if (
        status is not ContextStatus.STALE
        or kind != "canonical"
        or start != 0
        or end != len(block)
    ):
        raise ManagedBlockError("expected must be exactly one canonical managed block")
    return block


def render_managed_block(rendered_map: str) -> bytes:
    if not isinstance(rendered_map, str):
        raise TypeError("rendered_map must be str")
    payload = rendered_map.encode("utf-8")
    return (
        CONTEXT_START
        + b"\n"
        + b"## Project map (generated by Hologram)\n\n"
        + b"Use this complete map for orientation, placement, reuse, and review. "
        + b"Read source bodies before changing behavior.\n\n"
        + b"```text\n"
        + payload
        + b"```\n"
        + b"Regenerate with: `hologram build`\n"
        + CONTEXT_END
        + b"\n"
    )


def inspect_managed_block(existing: bytes, expected: bytes) -> ContextStatus:
    authored = _require_bytes(existing, "existing")
    candidate = _require_bytes(expected, "expected")
    status, kind, start, end = _managed_range(authored)
    if status is ContextStatus.MALFORMED:
        return status
    block = _validated_expected(candidate)
    if status is ContextStatus.MISSING:
        return status
    if kind == "legacy":
        return ContextStatus.STALE
    if start is None or end is None:
        raise AssertionError("valid managed pair is missing its byte range")
    return ContextStatus.FRESH if authored[start:end] == block else ContextStatus.STALE


def replace_managed_block(existing: bytes, expected: bytes) -> bytes:
    authored = _require_bytes(existing, "existing")
    candidate = _require_bytes(expected, "expected")
    status, kind, start, end = _managed_range(authored)
    if status is ContextStatus.MALFORMED:
        raise ManagedBlockError("existing context has malformed managed markers")
    block = _validated_expected(candidate)
    if status is ContextStatus.MISSING:
        separator = b"" if not authored or authored.endswith((b"\n", b"\r")) else b"\n"
        return authored + separator + block
    if start is None or end is None or kind is None:
        raise AssertionError("valid managed pair is missing its byte range")
    if kind == "canonical" and authored[start:end] == block:
        return existing
    return authored[:start] + block + authored[end:]


__all__ = [
    "AGENT_PATHS",
    "CONTEXT_END",
    "CONTEXT_START",
    "LEGACY_END",
    "LEGACY_START",
    "ContextStatus",
    "ManagedBlockError",
    "inspect_managed_block",
    "render_managed_block",
    "replace_managed_block",
]
