"""CLI commands and the self-installing git hooks."""
from __future__ import annotations

import argparse
import difflib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from ._version import __version__
from .bootstrap import (_bootstrap_or_die, _missing_parser_langs, _pyz_path,
                        _venv_python)
from .embed import (_block_span, _target_candidates, context_targets,
                    embed_digest, embedded_digest, managed_context_cost)
from .extract import EXTRACTORS
from .gather import (_digest_budget, _digest_langs, _digest_state,
                     _digest_targets, _git_env,
                     _state_hash, scan_files)
from .render import build_digest, build_digest_with_stats, estimate_tokens
from .symbols import DENYLIST_DIRS, detect_language


# ---------------------------------------------------------------------------
# CLI: build / init (self-installing git hooks)
# ---------------------------------------------------------------------------

HOOK_NAMES = ("post-commit", "post-merge", "post-checkout")
# Containment protects a context *write*. Only these commands write one, so
# only these enforce it; read-only commands stay usable in a repository whose
# context file is a legitimate symlink into shared guidance.
_CONTEXT_WRITING_COMMANDS = ("build", "init")
# Hooks installed today versus every hook that may contain a line managed by a
# released Hologram version. 0.8 briefly installed a review-only pre-commit
# hook; current installs must remove that line or users receive two reviews.
_MANAGED_HOOK_NAMES = ("pre-commit", *HOOK_NAMES)
_HOOK_MARKER = "# hologram:managed"


def _hook_python() -> str:
    """The tool's own venv python when present (tree-sitter grammars), else python3."""
    venv_py = _venv_python()
    return str(venv_py) if venv_py.exists() else "python3"


def _sh_dq(s: str) -> str:
    """Escape a path for interpolation inside a double-quoted shell word.
    Without this a directory named `x$(cmd)` would execute when the hook runs."""
    if '"' in s or "\n" in s:
        raise SystemExit("hologram: refusing to write a git hook for a path "
                         "containing a double quote or newline: " + s)
    return s.replace("\\", "\\\\").replace("$", "\\$").replace("`", "\\`")


def _tool_invocation() -> str:
    """Command prefix a hook uses to run hologram — the same delivery mode that is
    running now: zipapp path, checkout shim, or `-m hologram` from a pip install."""
    pyz = _pyz_path()
    if pyz is not None:
        return f'"{_sh_dq(_hook_python())}" "{_sh_dq(str(pyz))}"'
    shim = Path(__file__).resolve().parent.parent / "hologram.py"
    if shim.is_file():
        return f'"{_sh_dq(_hook_python())}" "{_sh_dq(str(shim))}"'
    return f'"{_sh_dq(sys.executable)}" -m hologram'


def _managed_hook_line(line: str, repo: Path) -> bool:
    """Recognize exact hook commands generated by current and older hologram:
    a quoted script/pyz path, or the `-m hologram` form. A managed marker is
    durable ownership evidence, so marked commands remain recognizable after
    the repository moves; unmarked legacy commands must name today's root."""
    executable = r'(?:"[^"\n]+"|\S+)'
    invocation = r'(?:"[^"\n]+hologram\.pyz?"|-m hologram)'
    repo_str = str(repo.resolve())
    roots = {repo_str}
    try:
        roots.add(_sh_dq(repo_str))  # current escaped form + pre-0.3.1 raw form
    except SystemExit:
        pass
    marked = line.endswith(f" {_HOOK_MARKER}")
    root_alt = (r'[^"\n]+' if marked else
                "|".join(re.escape(r) for r in sorted(roots)))
    tail = (rf' \|\| true {re.escape(_HOOK_MARKER)}$' if marked else
            r' \|\| true$')
    build_form = (
        rf'^{executable} {invocation} build --root '
        rf'"(?:{root_alt})"(?: --lang \S+)*'
        rf'(?: --(?:no-)?embed)? --quiet'
        rf'(?: && {executable} {invocation} review \S+ --root '
        rf'"(?:{root_alt})" --quiet-if-clean)?'  # 0.7.0 post-commit form
        + tail
    )
    review_form = (
        rf'^{executable} {invocation} review \S+ --root '
        rf'"(?:{root_alt})" --quiet-if-clean'
        + tail
    )
    return (re.fullmatch(build_form, line) is not None
            or re.fullmatch(review_form, line) is not None)


def _dead_hook_scripts(repo: Path) -> set[str]:
    """Managed hook lines whose quoted script path no longer exists — e.g. hooks
    installed by a since-upgraded pip install. `|| true` hides their failure."""
    dead: set[str] = set()
    for name in _MANAGED_HOOK_NAMES:
        hook = repo / ".git" / "hooks" / name
        if not hook.is_file():
            continue
        for line in hook.read_text().splitlines():
            if _managed_hook_line(line, repo):
                m = re.search(
                    r' "([^"\n]+hologram\.pyz?)" (?:build|review \S+) --root ',
                    line)
                if m and not Path(m.group(1)).exists():
                    dead.add(m.group(1))
    return dead


def _remove_managed_hook_lines(repo: Path, name: str) -> bool:
    """Remove only Hologram-owned lines from one hook, preserving foreign
    commands. Delete the file when nothing but its shebang remains."""
    hook = repo / ".git" / "hooks" / name
    if not hook.is_file():
        return False
    lines = hook.read_text().splitlines()
    kept = [line for line in lines if not _managed_hook_line(line, repo)]
    if len(kept) == len(lines):
        return False
    if all(not line.strip() or line.startswith("#!") for line in kept):
        hook.unlink()
    else:
        hook.write_text("\n".join(kept) + "\n")
    return True


def _install_hooks(repo: Path, quiet: bool, langs: set[str] | None = None) -> None:
    lang_args = "".join(f' --lang {l}' for l in sorted(langs)) if langs else ""
    root_q = _sh_dq(str(repo.resolve()))
    build_part = (f'{_tool_invocation()} build --root "{root_q}"'
                  f'{lang_args} --quiet')
    # only the post-commit hook reviews: HEAD~1 is meaningless after a merge
    # or checkout, and its stdout is what lands in the committing agent's
    # context when there are findings. A pre-commit timing variant was built
    # and measured for 0.8.0 — findings fired identically but no agent acted
    # any more than post-commit, so the known-quantity form stays.
    review_part = (f' && {_tool_invocation()} review HEAD~1 --root "{root_q}"'
                   f' --quiet-if-clean')
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    # Migrate the measured-and-reverted 0.8 timing experiment. Foreign
    # pre-commit commands remain byte-for-byte lines in the hook.
    _remove_managed_hook_lines(repo, "pre-commit")
    for name in HOOK_NAMES:
        hook_line = (build_part
                     + (review_part if name == "post-commit" else "")
                     + f' || true {_HOOK_MARKER}\n')
        hook = hooks_dir / name
        if hook.exists():
            content = hook.read_text()
            lines = content.splitlines()
            managed = [i for i, line in enumerate(lines)
                       if _managed_hook_line(line, repo)]
            if managed:
                first = managed[0]
                lines[first] = hook_line.rstrip("\n")
                lines = [line for i, line in enumerate(lines)
                         if i == first or i not in managed]
                hook.write_text("\n".join(lines) + "\n")
            else:
                hook.write_text(content.rstrip("\n") + "\n" + hook_line)
        else:
            hook.write_text("#!/bin/sh\n" + hook_line)
        hook.chmod(0o755)
    if not quiet:
        print(f"hooks installed: {', '.join(HOOK_NAMES)}")


def _strip_block(root: Path, t: Path) -> str | None:
    """Remove the managed block while preserving the context file itself.

    A conventional Hologram basename and canonical front matter do not prove
    that Hologram created the file; a user may have authored exactly that file
    before installation. Without durable provenance, deletion is unsafe.
    """
    if not t.is_file():
        return None
    existing = t.read_text()
    span = _block_span(existing)
    if span is None:
        return None
    cleaned = (existing[:span[0]] + existing[span[1]:]).strip("\n")
    t.write_text(cleaned + "\n" if cleaned else "")
    return str(t.relative_to(root))


def _uninstall(root: Path, keep_blocks: bool, quiet: bool) -> None:
    """Remove managed hook lines (deleting a hook file left with only its shebang)
    and, unless keep_blocks, strip embedded map blocks while preserving their
    context files."""
    removed: list[str] = []
    hooks_dir = root / ".git" / "hooks"
    for name in _MANAGED_HOOK_NAMES:
        hook = hooks_dir / name
        existed = hook.is_file()
        if not _remove_managed_hook_lines(root, name):
            continue
        suffix = " (deleted)" if existed and not hook.exists() else ""
        removed.append(f".git/hooks/{name}{suffix}")
    if not keep_blocks:
        for t in context_targets(root):
            # Hook removal must always succeed. An aliased context file is
            # skipped with a warning rather than aborting the uninstall.
            try:
                _contained_target(root, t, "context target")
            except SystemExit as exc:
                print(f"hologram: warning: {exc} — leaving its block in place",
                      file=sys.stderr)
                continue
            stripped = _strip_block(root, t)
            if stripped is not None:
                removed.append(stripped)
    if not quiet:
        print("removed: " + (", ".join(removed) if removed else "nothing"))


def _warn_if_large(digest: str, threshold: int, *, managed: bool = False) -> None:
    tokens = (managed_context_cost(digest).managed_block_tokens
              if managed else estimate_tokens(digest))
    if threshold and tokens > threshold:
        subject = "managed context" if managed else "map"
        print(f"hologram: warning: the {subject} is ~{tokens:,} tokens "
              f"(threshold {threshold:,}) — that is a lot of always-loaded "
              f"context. Consider --lang filters to narrow it. The map was "
              f"still written exactly; raise or disable with --warn-tokens.",
              file=sys.stderr)


def _contained_target(root: Path, target: Path, label: str) -> Path:
    """Return a context target only when it cannot alias another file.

    Resolving inside the repository is insufficient: an in-root symlink can
    redirect a context write onto source code, and a hard link can modify an
    alias outside the repository. Reject either form before reading or writing.
    """
    resolved_root = root.resolve()
    try:
        relative = target.relative_to(resolved_root)
        target.resolve().relative_to(resolved_root)
    except ValueError:
        raise SystemExit(f"{label} escapes repository: {target}") from None

    component = resolved_root
    for part in relative.parts:
        component /= part
        if component.is_symlink():
            raise SystemExit(f"{label} is a symlink: {target}")

    if target.is_file() and target.stat().st_nlink > 1:
        raise SystemExit(f"{label} has multiple hard links: {target}")
    return target


def _resolve_target_restriction(root: Path, wanted: list[str], *,
                                stored: bool, verify: bool = True
                                ) -> tuple[list[str], list[Path]]:
    """Resolve CLI or persisted target names against the fixed supported
    candidate set. Persisted names must be exact repository-relative paths;
    CLI names may use an unambiguous basename for convenience. `verify`
    enforces containment — required before a write, skipped for read-only
    commands so an aliased target cannot make them unusable."""
    candidates = _target_candidates(root)
    resolved: list[Path] = []
    for name in wanted:
        exact = [candidate for candidate in candidates
                 if str(candidate.relative_to(root)) == name]
        by_name = ([] if stored else
                   [candidate for candidate in candidates
                    if candidate.name == name])
        matches = exact or by_name
        if len(matches) != 1:
            if stored:
                raise SystemExit(f"invalid stored target restriction: {name}")
            listing = ", ".join(str(candidate.relative_to(root))
                                for candidate in candidates)
            kind = "ambiguous" if len(matches) > 1 else "unknown"
            raise SystemExit(f"{kind} target: {name}\ncandidates: {listing}")
        candidate = (_contained_target(
            root, matches[0], "stored target" if stored else "target")
            if verify else matches[0])
        if candidate not in resolved:
            resolved.append(candidate)
    names = sorted(str(path.relative_to(root)) for path in resolved)
    by_rel = {str(path.relative_to(root)): path for path in resolved}
    return names, [by_rel[name] for name in names]


def _revision_source_paths(root: Path, rev: str) -> list[Path]:
    """Source paths tracked by ``rev``, including files absent from disk now.

    Review and diff parse both snapshots. Parser bootstrapping therefore needs
    the union of working-tree and baseline languages before either extraction
    begins; ``scan_files`` alone cannot see a deleted last file of a language.
    An invalid revision is left to the normal worktree error for compatibility.
    """
    try:
        result = subprocess.run(
            ["git", "-C", str(root), "ls-tree", "-r", "--name-only", "-z",
             rev],
            capture_output=True, text=True, timeout=60, env=_git_env())
    except (OSError, subprocess.TimeoutExpired):
        return []
    if result.returncode != 0:
        return []
    paths: list[Path] = []
    for raw in result.stdout.split("\0"):
        rel = Path(raw)
        if (not raw or detect_language(rel) is None
                or any(part in DENYLIST_DIRS or part.startswith(".")
                       for part in rel.parts[:-1])):
            continue
        paths.append(root / rel)
    return sorted(paths)


def run_cli(argv: list[str] | None = None) -> int:
    def add_root(command: argparse.ArgumentParser) -> None:
        command.add_argument("--root", type=Path, default=Path.cwd())

    def add_lang(command: argparse.ArgumentParser) -> None:
        command.add_argument(
            "--lang", action="append", default=None,
            help="restrict to supported extractor name(s), repeatable or "
                 "comma-separated (for example: python, java, typescript). "
                 "Build/init record the filter for later rebuilds; --lang all "
                 "selects every language")

    def add_target(command: argparse.ArgumentParser) -> None:
        command.add_argument(
            "--target", action="append", default=None,
            help="select context file(s), repeatable or comma-separated "
                 "(CLAUDE.md, AGENTS.md, .cursor/rules/hologram.mdc, …). "
                 "Build/init record the selection; --target all "
                 "restores auto-detection")

    def add_budget(command: argparse.ArgumentParser) -> None:
        command.add_argument(
            "--budget", type=int, default=None, metavar="N",
            help="estimated digest-token target; over budget, keep the compact "
                 "semantic floor, then globally restore ranked, dependency-"
                 "closed whole facts. If the floor cannot fit, emit the "
                 "smallest complete candidate with a warning. Build/init "
                 "record it; --budget 0 selects unlimited")

    def add_quiet(command: argparse.ArgumentParser) -> None:
        command.add_argument("--quiet", action="store_true")

    def add_warn_tokens(command: argparse.ArgumentParser) -> None:
        command.add_argument(
            "--warn-tokens", type=int, default=25000, metavar="N",
            help="warn on stderr when the map exceeds N estimated tokens "
                 "(0 disables; output is still complete)")

    def add_map_options(command: argparse.ArgumentParser, *, quiet: bool,
                        warn: bool) -> None:
        add_root(command)
        add_lang(command)
        add_target(command)
        add_budget(command)
        if quiet:
            add_quiet(command)
        if warn:
            add_warn_tokens(command)

    _COMPAT_OPTIONS = {
        "--lang": dict(action="append", default=None),
        "--target": dict(action="append", default=None),
        "--budget": dict(type=int, default=None),
        "--quiet": dict(action="store_true"),
        "--warn-tokens": dict(type=int, default=25000),
    }

    def add_compat_options(command: argparse.ArgumentParser,
                           *names: str) -> None:
        """Accept-and-ignore the options every 0.9.0 subcommand took.

        They are hidden from --help because they do nothing here, but removing
        them outright would break scripts that pass them uniformly."""
        for name in names:
            command.add_argument(name, help=argparse.SUPPRESS,
                                 **_COMPAT_OPTIONS[name])

    parser = argparse.ArgumentParser(prog="hologram", description=__doc__)
    parser.add_argument("--version", action="version",
                        version=f"hologram {__version__}")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_build = sub.add_parser("build",
                             help="(re)generate the map in agent context files")
    add_map_options(p_build, quiet=True, warn=True)
    p_build.add_argument("--if-stale", action="store_true",
                         help="skip the rebuild when the embedded map's state stamp "
                              "matches the current sources")
    p_init = sub.add_parser("init", help="install git hooks, then build")
    add_map_options(p_init, quiet=True, warn=True)
    p_check = sub.add_parser(
        "check", help="exit 0 if the embedded map is fresh, 1 if stale or missing")
    add_root(p_check)
    add_lang(p_check)
    add_target(p_check)
    add_quiet(p_check)
    add_compat_options(p_check, "--budget", "--warn-tokens")
    p_diff = sub.add_parser("diff",
                            help="diff the map against another git revision")
    add_root(p_diff)
    add_lang(p_diff)
    add_compat_options(p_diff, "--target", "--budget", "--quiet",
                       "--warn-tokens")
    p_diff.add_argument("rev", nargs="?", default="HEAD~1")
    p_rev = sub.add_parser("review",
                           help="deterministic drift review of the working tree "
                                "vs a revision: duplicates, re-coverage, dead "
                                "arrivals, orphaned tests, API drift, placement")
    add_root(p_rev)
    add_lang(p_rev)
    add_compat_options(p_rev, "--target", "--budget", "--quiet",
                       "--warn-tokens")
    p_rev.add_argument("rev", nargs="?", default="HEAD")
    p_rev.add_argument("--quiet-if-clean", action="store_true",
                       help="print nothing when there are no findings")
    p_rev.add_argument("--brief", type=int, default=None, metavar="K",
                       help="API-drift summary over the last K commits only")
    p_rev.add_argument("--json", action="store_true",
                       help="emit stable finding IDs and structured metadata as JSON")
    p_stats = sub.add_parser(
        "stats",
        help="inspect token-budget selection without writing context files")
    add_map_options(p_stats, quiet=False, warn=False)
    add_compat_options(p_stats, "--quiet", "--warn-tokens")
    p_stats.add_argument("--json", action="store_true",
                         help="emit the complete budget decision as JSON")
    p_print = sub.add_parser(
        "print", help="write the map to stdout without modifying context or "
                      "source files")
    add_map_options(p_print, quiet=False, warn=True)
    add_compat_options(p_print, "--quiet")
    p_un = sub.add_parser("uninstall",
                          help="remove managed hook lines and embedded map blocks")
    add_root(p_un)
    add_quiet(p_un)
    add_compat_options(p_un, "--lang", "--target", "--budget", "--warn-tokens")
    p_un.add_argument("--keep-blocks", action="store_true",
                      help="remove only the git hooks, leave embedded maps in place")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    writes_context = args.cmd in _CONTEXT_WRITING_COMMANDS
    targets = context_targets(root)
    if writes_context:
        targets = [_contained_target(root, target, "context target")
                   for target in targets]
    target_names: list[str] | None = None
    restricted_targets: list[Path] | None = None
    if getattr(args, "target", None):
        wanted = [t.strip() for arg in args.target for t in arg.split(",")
                  if t.strip()]
        if wanted == ["all"]:
            target_names = None  # explicit reset of a stored restriction
        else:
            target_names, restricted_targets = _resolve_target_restriction(
                root, wanted, stored=False, verify=writes_context)
    langs = None
    if getattr(args, "lang", None):
        langs = {l.strip() for arg in args.lang for l in arg.split(",") if l.strip()}
        if langs == {"all"}:
            langs = None  # explicit reset of a stored filter
        else:
            unknown = langs - set(EXTRACTORS)
            if unknown:
                raise SystemExit(
                    f"unknown language{'s' if len(unknown) > 1 else ''}: "
                    f"{', '.join(sorted(unknown))}\n"
                    f"known: {', '.join(sorted(EXTRACTORS))}")
    else:
        # no --lang given: recall the filter a previous build stamped into the map
        for t in targets:
            stored = _digest_langs(embedded_digest(t))
            if stored:
                langs = stored & set(EXTRACTORS) or None
                break
    if target_names is None and not getattr(args, "target", None):
        # no --target given: recall a stored restriction the same way
        for t in targets:
            stored_t = _digest_targets(embedded_digest(t))
            if stored_t:
                target_names, restricted_targets = _resolve_target_restriction(
                    root, stored_t, stored=True, verify=writes_context)
                break
    budget = getattr(args, "budget", None)
    if budget is not None and budget < 0:
        raise SystemExit("--budget must be a positive integer, or 0 to clear")
    if budget == 0:
        budget = None  # explicit reset of a stored budget
    elif budget is None:
        for t in targets:
            stored_b = _digest_budget(embedded_digest(t))
            if stored_b:
                budget = stored_b
                break
    if target_names is not None:
        deselected = [t for t in targets
                      if str(t.relative_to(root)) not in target_names]
        if restricted_targets is None:
            target_names, restricted_targets = _resolve_target_restriction(
                root, target_names, stored=True, verify=writes_context)
        targets = restricted_targets
        if getattr(args, "target", None) and args.cmd in ("build", "init"):
            for t in deselected:
                _strip_block(root, t)
    state = _state_hash(root, langs)
    stale = [t for t in targets if _digest_state(embedded_digest(t)) != state]

    if args.cmd == "check":
        if not args.quiet:
            for t in targets:
                mark = "stale or missing" if t in stale else "fresh"
                print(f"{t.relative_to(root)}: {mark}")
        return 1 if stale else 0
    if args.cmd == "uninstall":
        _uninstall(root, args.keep_blocks, args.quiet)
        return 0
    if args.cmd == "build" and args.if_stale and not stale:
        # The state hash covers sources, not settings. A changed --budget
        # leaves every stamp fresh, so without this the rebuild is skipped and
        # the map silently keeps the previous budget. `check` deliberately
        # stays source-only: its own --budget is an accept-and-ignore option.
        if all(_digest_budget(embedded_digest(t)) == budget for t in targets):
            if not args.quiet:
                print("fresh, skipping rebuild")
            return 0
    review_rev: str | None = None
    review_checks: frozenset[str] | None = None
    if args.cmd == "review":
        review_rev = args.rev
        if args.brief is not None:
            if args.rev != "HEAD":
                raise SystemExit("--brief K and an explicit revision are "
                                 "mutually exclusive")
            review_rev = f"HEAD~{args.brief}"
            review_checks = frozenset({"api"})
    comparison_rev = (review_rev if args.cmd == "review" else
                      args.rev if args.cmd == "diff" else None)
    files = scan_files(root)
    if comparison_rev is not None:
        files.extend(_revision_source_paths(root, comparison_rev))
    if langs is not None:
        files = [f for f in files if detect_language(f) in langs]
    missing = _missing_parser_langs(files)
    if missing:
        _bootstrap_or_die(missing, argv if argv is not None else sys.argv[1:])

    if args.cmd == "review":
        from .review import run_review, run_review_data
        assert review_rev is not None
        if args.json:
            print(json.dumps(
                run_review_data(root, review_rev, langs=langs,
                                checks=review_checks),
                sort_keys=True, separators=(",", ":")))
            return 0  # findings are informational, never a gate
        report = run_review(root, review_rev, langs=langs,
                            checks=review_checks)
        if report:
            print(report, end="")
        elif not args.quiet_if_clean:
            print(f"hologram review: no findings vs {review_rev}")
        return 0  # findings are informational, never a gate

    if args.cmd == "diff":
        with tempfile.TemporaryDirectory(prefix="hologram-diff-") as tmp:
            wt = Path(tmp) / "wt"
            r = subprocess.run(
                ["git", "-C", str(root), "worktree", "add", "--detach", "-f",
                 str(wt), args.rev],
                capture_output=True, text=True, env=_git_env())
            if r.returncode != 0:
                raise SystemExit(f"git worktree failed: {r.stderr.strip()}")
            try:
                old = build_digest(wt, langs=langs)
                new = build_digest(root, langs=langs)
            finally:
                subprocess.run(["git", "-C", str(root), "worktree", "remove",
                                "--force", str(wt)], capture_output=True,
                               env=_git_env())
        def semantic_lines(digest: str) -> list[str]:
            lines = digest.splitlines()[2:]  # stable title + notation line
            if lines and re.match(r"^· [\d,]+ LOC(?: ·|$)", lines[-1]):
                lines.pop()  # volatile cache-stability footer is not a code fact
            return lines

        body_old = semantic_lines(old)
        body_new = semantic_lines(new)
        for ln in difflib.unified_diff(body_old, body_new, fromfile=args.rev,
                                       tofile="worktree", lineterm=""):
            print(ln)
        return 0

    if args.cmd == "stats":
        digest, stats = build_digest_with_stats(
            root, langs=langs, targets=target_names, budget=budget)
        payload = stats.as_dict()
        context_cost = managed_context_cost(digest)
        payload.update({
            "digest_tokens": context_cost.digest_tokens,
            "wrapper_tokens": context_cost.wrapper_tokens,
            "coaching_tokens": context_cost.coaching_tokens,
            "managed_block_tokens": context_cost.managed_block_tokens,
        })
        if args.json:
            print(json.dumps(payload, sort_keys=True, separators=(",", ":")))
        else:
            budget_text = (f"{stats.requested_budget:,}"
                           if stats.requested_budget else "unlimited")
            utilization = (f"{stats.utilization:.1%}"
                           if stats.utilization is not None else "—")
            retained = len(stats.retained_bundles)
            dropped = len(stats.dropped_bundles)
            print(f"policy: {stats.policy_version}")
            print(f"budget: {budget_text} · fits: "
                  f"{'yes' if stats.fits else 'no'} · utilization: {utilization}")
            print(f"tokens: selected digest {stats.selected_tokens:,} · "
                  f"full {stats.full_tokens:,} · "
                  f"skeleton {stats.skeleton_tokens:,}")
            print(f"managed block: {context_cost.managed_block_tokens:,} · "
                  f"wrapper {context_cost.wrapper_tokens:,} · "
                  f"coaching {context_cost.coaching_tokens:,}")
            print(f"detail: {stats.effective_detail} · "
                  f"bundles retained {retained:,} · dropped {dropped:,}")
            if stats.retained_reasons:
                reason_text = ", ".join(
                    f"{reason}={count}"
                    for reason, count in stats.retained_reasons)
                print(f"retained for: {reason_text}")
            print(f"search: {stats.stop_reason} · "
                  f"trials {stats.selection_trials:,} · "
                  f"candidates {stats.selection_candidates:,}"
                  + (" · truncated" if stats.search_truncated else ""))
        return 0

    if args.cmd == "print":
        digest = build_digest(root, langs=langs, targets=target_names,
                              budget=budget)
        if not budget:
            _warn_if_large(digest, args.warn_tokens)
        print(digest, end="")
        return 0

    if args.cmd == "init":
        _install_hooks(root, args.quiet, langs)
    for script in sorted(_dead_hook_scripts(root)):
        print(f"hologram: warning: a git hook still points at {script}, which no "
              f"longer exists — run `hologram init --root {root}` to repair it",
              file=sys.stderr)
    digest = build_digest(root, langs=langs, targets=target_names,
                          budget=budget)
    _warn_if_large(digest, args.warn_tokens, managed=True)
    for t in targets:
        embed_digest(t, digest)
    if not args.quiet:
        names = ", ".join(str(t.relative_to(root)) for t in targets)
        cost = managed_context_cost(digest)
        # Keep the documented leading digest count for scripts consuming old
        # output, while making the complete always-loaded cost explicit.
        print(f"hologram: {cost.digest_tokens} tokens embedded in {names} "
              f"(digest; managed {cost.managed_block_tokens} = wrapper "
              f"{cost.wrapper_tokens} + coaching {cost.coaching_tokens} + "
              f"digest {cost.digest_tokens})")
    return 0



def main() -> None:
    raise SystemExit(run_cli())
