"""CLI commands and the self-installing git hooks."""
from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from ._version import __version__
from .bootstrap import (_bootstrap_or_die, _missing_parser_langs, _pyz_path,
                        _venv_python)
from .embed import (_block_span, _target_candidates, context_targets,
                    embed_digest, embedded_digest)
from .extract import EXTRACTORS
from .gather import (_digest_langs, _digest_state, _digest_targets,
                     _state_hash, scan_files)
from .render import build_digest, estimate_tokens
from .symbols import detect_language


# ---------------------------------------------------------------------------
# CLI: build / init (self-installing git hooks)
# ---------------------------------------------------------------------------

HOOK_NAMES = ("post-commit", "post-merge", "post-checkout")
_HOOK_MARKER = "# hologram:managed"


def _hook_python() -> str:
    """The tool's own venv python when present (tree-sitter grammars), else python3."""
    venv_py = _venv_python()
    return str(venv_py) if venv_py.exists() else "python3"


def _sh_dq(s: str) -> str:
    """Escape a path for interpolation inside a double-quoted shell word.
    Without this a directory named `x$(cmd)` would execute when the hook runs."""
    if '"' in s or "\n" in s:
        raise SystemExit("hologram: refusing to write a git hook for a path "
                         "containing a double quote or newline: " + s)
    return s.replace("\\", "\\\\").replace("$", "\\$").replace("`", "\\`")


def _tool_invocation() -> str:
    """Command prefix a hook uses to run hologram — the same delivery mode that is
    running now: zipapp path, checkout shim, or `-m hologram` from a pip install."""
    pyz = _pyz_path()
    if pyz is not None:
        return f'"{_sh_dq(_hook_python())}" "{_sh_dq(str(pyz))}"'
    shim = Path(__file__).resolve().parent.parent / "hologram.py"
    if shim.is_file():
        return f'"{_sh_dq(_hook_python())}" "{_sh_dq(str(shim))}"'
    return f'"{_sh_dq(sys.executable)}" -m hologram'


def _managed_hook_line(line: str, repo: Path) -> bool:
    """Recognize exact hook commands generated by current and older hologram:
    a quoted script/pyz path, or the `-m hologram` form."""
    executable = r'(?:"[^"\n]+"|\S+)'
    invocation = r'(?:"[^"\n]+hologram\.pyz?"|-m hologram)'
    repo_str = str(repo.resolve())
    roots = {repo_str}
    try:
        roots.add(_sh_dq(repo_str))  # current escaped form + pre-0.3.1 raw form
    except SystemExit:
        pass
    root_alt = "|".join(re.escape(r) for r in sorted(roots))
    pattern = (
        rf'^{executable} {invocation} build --root '
        rf'"(?:{root_alt})"(?: --lang \S+)*'
        rf'(?: --(?:no-)?embed)? --quiet'
        rf'(?: && {executable} {invocation} review \S+ --root '
        rf'"(?:{root_alt})" --quiet-if-clean)?'
        rf' \|\| true'
        rf'(?: {re.escape(_HOOK_MARKER)})?$'
    )
    return re.fullmatch(pattern, line) is not None


def _dead_hook_scripts(repo: Path) -> set[str]:
    """Managed hook lines whose quoted script path no longer exists — e.g. hooks
    installed by a since-upgraded pip install. `|| true` hides their failure."""
    dead: set[str] = set()
    for name in HOOK_NAMES:
        hook = repo / ".git" / "hooks" / name
        if not hook.is_file():
            continue
        for line in hook.read_text().splitlines():
            if _managed_hook_line(line, repo):
                m = re.search(r' "([^"\n]+hologram\.pyz?)" build --root ', line)
                if m and not Path(m.group(1)).exists():
                    dead.add(m.group(1))
    return dead


def _install_hooks(repo: Path, quiet: bool, langs: set[str] | None = None) -> None:
    lang_args = "".join(f' --lang {l}' for l in sorted(langs)) if langs else ""
    root_q = _sh_dq(str(repo.resolve()))
    build_part = (f'{_tool_invocation()} build --root "{root_q}"'
                  f'{lang_args} --quiet')
    # only the post-commit hook reviews: HEAD~1 is meaningless after a merge
    # or checkout, and its stdout is what lands in the committing agent's
    # context when there are findings
    review_part = (f' && {_tool_invocation()} review HEAD~1 --root "{root_q}"'
                   f' --quiet-if-clean')
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    for name in HOOK_NAMES:
        hook_line = (build_part
                     + (review_part if name == "post-commit" else "")
                     + f' || true {_HOOK_MARKER}\n')
        hook = hooks_dir / name
        if hook.exists():
            content = hook.read_text()
            lines = content.splitlines()
            managed = [i for i, line in enumerate(lines)
                       if _managed_hook_line(line, repo)]
            if managed:
                first = managed[0]
                lines[first] = hook_line.rstrip("\n")
                lines = [line for i, line in enumerate(lines)
                         if i == first or i not in managed]
                hook.write_text("\n".join(lines) + "\n")
            else:
                hook.write_text(content.rstrip("\n") + "\n" + hook_line)
        else:
            hook.write_text("#!/bin/sh\n" + hook_line)
        hook.chmod(0o755)
    if not quiet:
        print(f"hooks installed: {', '.join(HOOK_NAMES)}")


_MANAGED_BASENAMES = ("hologram.md", "hologram.mdc", "hologram.instructions.md")


def _strip_block(root: Path, t: Path) -> str | None:
    """Remove the managed block from one context file: rule files hologram
    itself created are deleted outright, others keep their prose. Returns a
    display string for reporting, or None if nothing changed."""
    if not t.is_file():
        return None
    if t.name in _MANAGED_BASENAMES:
        t.unlink()
        return f"{t.relative_to(root)} (deleted)"
    existing = t.read_text()
    span = _block_span(existing)
    if span is None:
        return None
    cleaned = (existing[:span[0]] + existing[span[1]:]).strip("\n")
    t.write_text(cleaned + "\n" if cleaned else "")
    return str(t.relative_to(root))


def _uninstall(root: Path, keep_blocks: bool, quiet: bool) -> None:
    """Remove managed hook lines (deleting a hook file left with only its shebang)
    and, unless keep_blocks, strip embedded map blocks — deleting outright the rule
    files hologram itself created inside rule directories."""
    removed: list[str] = []
    hooks_dir = root / ".git" / "hooks"
    for name in HOOK_NAMES:
        hook = hooks_dir / name
        if not hook.is_file():
            continue
        lines = hook.read_text().splitlines()
        kept = [l for l in lines if not _managed_hook_line(l, root)]
        if len(kept) == len(lines):
            continue
        if all(not l.strip() or l.startswith("#!") for l in kept):
            hook.unlink()
            removed.append(f".git/hooks/{name} (deleted)")
        else:
            hook.write_text("\n".join(kept) + "\n")
            removed.append(f".git/hooks/{name}")
    if not keep_blocks:
        for t in context_targets(root):
            stripped = _strip_block(root, t)
            if stripped is not None:
                removed.append(stripped)
    if not quiet:
        print("removed: " + (", ".join(removed) if removed else "nothing"))


def _warn_if_large(digest: str, threshold: int) -> None:
    tokens = estimate_tokens(digest)
    if threshold and tokens > threshold:
        print(f"hologram: warning: the map is ~{tokens:,} tokens "
              f"(threshold {threshold:,}) — that is a lot of always-loaded "
              f"context. Consider --lang filters to narrow it. The map was "
              f"still written exactly; raise or disable with --warn-tokens.",
              file=sys.stderr)


def run_cli(argv: list[str] | None = None) -> int:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--root", type=Path, default=Path.cwd())
    common.add_argument("--lang", action="append", default=None,
                        help="restrict to language(s), repeatable or comma-separated "
                             "(java, python, typescript, javascript). The filter is "
                             "recorded in the map and reused by later rebuilds; "
                             "--lang all clears it")
    common.add_argument("--target", action="append", default=None,
                        help="embed only into the named context file(s), "
                             "repeatable or comma-separated (CLAUDE.md, "
                             "AGENTS.md, .cursor/rules/hologram.mdc, …). "
                             "Recorded in the map and reused by later "
                             "rebuilds; blocks in deselected files are "
                             "removed; --target all restores auto-detection")
    common.add_argument("--quiet", action="store_true")
    common.add_argument("--warn-tokens", type=int, default=25000, metavar="N",
                        help="warn on stderr when the map exceeds N estimated "
                             "tokens (0 disables; the map is still written exactly)")

    parser = argparse.ArgumentParser(prog="hologram", description=__doc__)
    parser.add_argument("--version", action="version",
                        version=f"hologram {__version__}")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_build = sub.add_parser("build", parents=[common],
                             help="(re)generate the map embedded in CLAUDE.md")
    p_build.add_argument("--if-stale", action="store_true",
                         help="skip the rebuild when the embedded map's state stamp "
                              "matches the current sources")
    sub.add_parser("init", parents=[common],
                   help="install git hooks, then build")
    sub.add_parser("check", parents=[common],
                   help="exit 0 if the embedded map is fresh, 1 if stale or missing")
    p_diff = sub.add_parser("diff", parents=[common],
                            help="diff the map against another git revision")
    p_diff.add_argument("rev", nargs="?", default="HEAD~1")
    p_rev = sub.add_parser("review", parents=[common],
                           help="deterministic drift review of the working tree "
                                "vs a revision: duplicates, re-coverage, dead "
                                "arrivals, orphaned tests, API drift, placement")
    p_rev.add_argument("rev", nargs="?", default="HEAD")
    p_rev.add_argument("--quiet-if-clean", action="store_true",
                       help="print nothing when there are no findings")
    p_rev.add_argument("--brief", type=int, default=None, metavar="K",
                       help="API-drift summary over the last K commits only")
    sub.add_parser("print", parents=[common],
                   help="write the map to stdout without touching any file")
    p_un = sub.add_parser("uninstall", parents=[common],
                          help="remove managed hook lines and embedded map blocks")
    p_un.add_argument("--keep-blocks", action="store_true",
                      help="remove only the git hooks, leave embedded maps in place")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    targets = context_targets(root)
    target_names: list[str] | None = None
    if getattr(args, "target", None):
        wanted = [t.strip() for arg in args.target for t in arg.split(",")
                  if t.strip()]
        if wanted == ["all"]:
            target_names = None  # explicit reset of a stored restriction
        else:
            candidates = _target_candidates(root)
            resolved: list[Path] = []
            for w in wanted:
                exact = [c for c in candidates
                         if str(c.relative_to(root)) == w]
                by_name = [c for c in candidates if c.name == w]
                match = exact or by_name
                if len(match) != 1:
                    listing = ", ".join(str(c.relative_to(root))
                                        for c in candidates)
                    kind_of = "ambiguous" if len(match) > 1 else "unknown"
                    raise SystemExit(f"{kind_of} target: {w}\n"
                                     f"candidates: {listing}")
                resolved.append(match[0])
            target_names = sorted(str(p.relative_to(root)) for p in resolved)
    langs = None
    if getattr(args, "lang", None):
        langs = {l.strip() for arg in args.lang for l in arg.split(",") if l.strip()}
        if langs == {"all"}:
            langs = None  # explicit reset of a stored filter
        else:
            unknown = langs - set(EXTRACTORS)
            if unknown:
                raise SystemExit(
                    f"unknown language{'s' if len(unknown) > 1 else ''}: "
                    f"{', '.join(sorted(unknown))}\n"
                    f"known: {', '.join(sorted(EXTRACTORS))}")
    else:
        # no --lang given: recall the filter a previous build stamped into the map
        for t in targets:
            stored = _digest_langs(embedded_digest(t))
            if stored:
                langs = stored & set(EXTRACTORS) or None
                break
    if target_names is None and not getattr(args, "target", None):
        # no --target given: recall a stored restriction the same way
        for t in targets:
            stored_t = _digest_targets(embedded_digest(t))
            if stored_t:
                target_names = stored_t
                break
    if target_names is not None:
        deselected = [t for t in targets
                      if str(t.relative_to(root)) not in target_names]
        targets = [root / n for n in target_names]
        if getattr(args, "target", None) and args.cmd in ("build", "init"):
            for t in deselected:
                _strip_block(root, t)
    state = _state_hash(root, langs)
    stale = [t for t in targets if _digest_state(embedded_digest(t)) != state]

    if args.cmd == "check":
        if not args.quiet:
            for t in targets:
                mark = "stale or missing" if t in stale else "fresh"
                print(f"{t.relative_to(root)}: {mark}")
        return 1 if stale else 0
    if args.cmd == "uninstall":
        _uninstall(root, args.keep_blocks, args.quiet)
        return 0
    if args.cmd == "build" and args.if_stale and not stale:
        if not args.quiet:
            print("fresh, skipping rebuild")
        return 0
    if args.cmd == "review":
        from .review import run_review
        rev = args.rev
        checks = None
        if args.brief is not None:
            if args.rev != "HEAD":
                raise SystemExit("--brief K and an explicit revision are "
                                 "mutually exclusive")
            rev = f"HEAD~{args.brief}"
            checks = frozenset({"api"})
        report = run_review(root, rev, langs=langs, checks=checks)
        if report:
            print(report, end="")
        elif not args.quiet_if_clean:
            print(f"hologram review: no findings vs {rev}")
        return 0  # informational, never a gate

    files = scan_files(root)
    if langs is not None:
        files = [f for f in files if detect_language(f) in langs]
    missing = _missing_parser_langs(files)
    if missing:
        _bootstrap_or_die(missing, argv if argv is not None else sys.argv[1:])

    if args.cmd == "diff":
        with tempfile.TemporaryDirectory(prefix="hologram-diff-") as tmp:
            wt = Path(tmp) / "wt"
            r = subprocess.run(
                ["git", "-C", str(root), "worktree", "add", "--detach", "-f",
                 str(wt), args.rev],
                capture_output=True, text=True)
            if r.returncode != 0:
                raise SystemExit(f"git worktree failed: {r.stderr.strip()}")
            try:
                old = build_digest(wt, langs=langs)
                new = build_digest(root, langs=langs)
            finally:
                subprocess.run(["git", "-C", str(root), "worktree", "remove",
                                "--force", str(wt)], capture_output=True)
        body_old = old.splitlines()[2:]  # drop state-bearing header + notation line
        body_new = new.splitlines()[2:]
        for ln in difflib.unified_diff(body_old, body_new, fromfile=args.rev,
                                       tofile="worktree", lineterm=""):
            print(ln)
        return 0

    if args.cmd == "print":
        digest = build_digest(root, langs=langs, targets=target_names)
        _warn_if_large(digest, args.warn_tokens)
        print(digest, end="")
        return 0

    if args.cmd == "init":
        _install_hooks(root, args.quiet, langs)
    for script in sorted(_dead_hook_scripts(root)):
        print(f"hologram: warning: a git hook still points at {script}, which no "
              f"longer exists — run `hologram init --root {root}` to repair it",
              file=sys.stderr)
    digest = build_digest(root, langs=langs, targets=target_names)
    _warn_if_large(digest, args.warn_tokens)
    for t in targets:
        embed_digest(t, digest)
    if not args.quiet:
        names = ", ".join(str(t.relative_to(root)) for t in targets)
        print(f"hologram: {estimate_tokens(digest)} tokens embedded in {names}")
    return 0



def main() -> None:
    raise SystemExit(run_cli())
