"""CLI commands and the self-installing git hooks."""
from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from ._version import __version__
from .bootstrap import (_bootstrap_or_die, _missing_parser_langs, _pyz_path,
                        _venv_python)
from .embed import _block_span, context_targets, embed_digest, embedded_digest
from .extract import EXTRACTORS
from .gather import _digest_langs, _digest_state, _state_hash, scan_files
from .render import build_digest, estimate_tokens
from .symbols import detect_language


# ---------------------------------------------------------------------------
# CLI: build / init (self-installing git hooks)
# ---------------------------------------------------------------------------

HOOK_NAMES = ("post-commit", "post-merge", "post-checkout")
_HOOK_MARKER = "# hologram:managed"


def _hook_python() -> str:
    """The tool's own venv python when present (tree-sitter grammars), else python3."""
    venv_py = _venv_python()
    return str(venv_py) if venv_py.exists() else "python3"


def _tool_invocation() -> str:
    """Command prefix a hook uses to run hologram — the same delivery mode that is
    running now: zipapp path, checkout shim, or `-m hologram` from a pip install."""
    pyz = _pyz_path()
    if pyz is not None:
        return f'"{_hook_python()}" "{pyz}"'
    shim = Path(__file__).resolve().parent.parent / "hologram.py"
    if shim.is_file():
        return f'"{_hook_python()}" "{shim}"'
    return f'"{sys.executable}" -m hologram'


def _managed_hook_line(line: str, repo: Path) -> bool:
    """Recognize exact hook commands generated by current and older hologram:
    a quoted script/pyz path, or the `-m hologram` form."""
    executable = r'(?:"[^"\n]+"|\S+)'
    invocation = r'(?:"[^"\n]+hologram\.pyz?"|-m hologram)'
    pattern = (
        rf'^{executable} {invocation} build --root '
        rf'"{re.escape(str(repo.resolve()))}"(?: --lang \S+)*'
        rf'(?: --(?:no-)?embed)? --quiet \|\| true'
        rf'(?: {re.escape(_HOOK_MARKER)})?$'
    )
    return re.fullmatch(pattern, line) is not None


def _dead_hook_scripts(repo: Path) -> set[str]:
    """Managed hook lines whose quoted script path no longer exists — e.g. hooks
    installed by a since-upgraded pip install. `|| true` hides their failure."""
    dead: set[str] = set()
    for name in HOOK_NAMES:
        hook = repo / ".git" / "hooks" / name
        if not hook.is_file():
            continue
        for line in hook.read_text().splitlines():
            if _managed_hook_line(line, repo):
                m = re.search(r' "([^"\n]+hologram\.pyz?)" build --root ', line)
                if m and not Path(m.group(1)).exists():
                    dead.add(m.group(1))
    return dead


def _install_hooks(repo: Path, quiet: bool, langs: set[str] | None = None) -> None:
    lang_args = "".join(f' --lang {l}' for l in sorted(langs)) if langs else ""
    hook_line = (f'{_tool_invocation()} build --root "{repo.resolve()}"'
                 f'{lang_args} --quiet || true {_HOOK_MARKER}\n')
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    for name in HOOK_NAMES:
        hook = hooks_dir / name
        if hook.exists():
            content = hook.read_text()
            lines = content.splitlines()
            managed = [i for i, line in enumerate(lines)
                       if _managed_hook_line(line, repo)]
            if managed:
                first = managed[0]
                lines[first] = hook_line.rstrip("\n")
                lines = [line for i, line in enumerate(lines)
                         if i == first or i not in managed]
                hook.write_text("\n".join(lines) + "\n")
            else:
                hook.write_text(content.rstrip("\n") + "\n" + hook_line)
        else:
            hook.write_text("#!/bin/sh\n" + hook_line)
        hook.chmod(0o755)
    if not quiet:
        print(f"hooks installed: {', '.join(HOOK_NAMES)}")


_MANAGED_BASENAMES = ("hologram.md", "hologram.mdc", "hologram.instructions.md")


def _uninstall(root: Path, keep_blocks: bool, quiet: bool) -> None:
    """Remove managed hook lines (deleting a hook file left with only its shebang)
    and, unless keep_blocks, strip embedded map blocks — deleting outright the rule
    files hologram itself created inside rule directories."""
    removed: list[str] = []
    hooks_dir = root / ".git" / "hooks"
    for name in HOOK_NAMES:
        hook = hooks_dir / name
        if not hook.is_file():
            continue
        lines = hook.read_text().splitlines()
        kept = [l for l in lines if not _managed_hook_line(l, root)]
        if len(kept) == len(lines):
            continue
        if all(not l.strip() or l.startswith("#!") for l in kept):
            hook.unlink()
            removed.append(f".git/hooks/{name} (deleted)")
        else:
            hook.write_text("\n".join(kept) + "\n")
            removed.append(f".git/hooks/{name}")
    if not keep_blocks:
        for t in context_targets(root):
            if not t.is_file():
                continue
            if t.name in _MANAGED_BASENAMES:
                t.unlink()
                removed.append(f"{t.relative_to(root)} (deleted)")
                continue
            existing = t.read_text()
            span = _block_span(existing)
            if span is None:
                continue
            cleaned = (existing[:span[0]] + existing[span[1]:]).strip("\n")
            t.write_text(cleaned + "\n" if cleaned else "")
            removed.append(str(t.relative_to(root)))
    if not quiet:
        print("removed: " + (", ".join(removed) if removed else "nothing"))


def _warn_if_large(digest: str, threshold: int) -> None:
    tokens = estimate_tokens(digest)
    if threshold and tokens > threshold:
        print(f"hologram: warning: the map is ~{tokens:,} tokens "
              f"(threshold {threshold:,}) — that is a lot of always-loaded "
              f"context. Consider --lang filters to narrow it. The map was "
              f"still written exactly; raise or disable with --warn-tokens.",
              file=sys.stderr)


def run_cli(argv: list[str] | None = None) -> int:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--root", type=Path, default=Path.cwd())
    common.add_argument("--lang", action="append", default=None,
                        help="restrict to language(s), repeatable or comma-separated "
                             "(java, python, typescript, javascript). The filter is "
                             "recorded in the map and reused by later rebuilds; "
                             "--lang all clears it")
    common.add_argument("--quiet", action="store_true")
    common.add_argument("--warn-tokens", type=int, default=25000, metavar="N",
                        help="warn on stderr when the map exceeds N estimated "
                             "tokens (0 disables; the map is still written exactly)")

    parser = argparse.ArgumentParser(prog="hologram", description=__doc__)
    parser.add_argument("--version", action="version",
                        version=f"hologram {__version__}")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_build = sub.add_parser("build", parents=[common],
                             help="(re)generate the map embedded in CLAUDE.md")
    p_build.add_argument("--if-stale", action="store_true",
                         help="skip the rebuild when the embedded map's state stamp "
                              "matches the current sources")
    sub.add_parser("init", parents=[common],
                   help="install git hooks, then build")
    sub.add_parser("check", parents=[common],
                   help="exit 0 if the embedded map is fresh, 1 if stale or missing")
    p_diff = sub.add_parser("diff", parents=[common],
                            help="diff the map against another git revision")
    p_diff.add_argument("rev", nargs="?", default="HEAD~1")
    sub.add_parser("print", parents=[common],
                   help="write the map to stdout without touching any file")
    p_un = sub.add_parser("uninstall", parents=[common],
                          help="remove managed hook lines and embedded map blocks")
    p_un.add_argument("--keep-blocks", action="store_true",
                      help="remove only the git hooks, leave embedded maps in place")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    targets = context_targets(root)
    langs = None
    if getattr(args, "lang", None):
        langs = {l.strip() for arg in args.lang for l in arg.split(",") if l.strip()}
        if langs == {"all"}:
            langs = None  # explicit reset of a stored filter
        else:
            unknown = langs - set(EXTRACTORS)
            if unknown:
                raise SystemExit(
                    f"unknown language{'s' if len(unknown) > 1 else ''}: "
                    f"{', '.join(sorted(unknown))}\n"
                    f"known: {', '.join(sorted(EXTRACTORS))}")
    else:
        # no --lang given: recall the filter a previous build stamped into the map
        for t in targets:
            stored = _digest_langs(embedded_digest(t))
            if stored:
                langs = stored & set(EXTRACTORS) or None
                break
    state = _state_hash(root, langs)
    stale = [t for t in targets if _digest_state(embedded_digest(t)) != state]

    if args.cmd == "check":
        if not args.quiet:
            for t in targets:
                mark = "stale or missing" if t in stale else "fresh"
                print(f"{t.relative_to(root)}: {mark}")
        return 1 if stale else 0
    if args.cmd == "uninstall":
        _uninstall(root, args.keep_blocks, args.quiet)
        return 0
    if args.cmd == "build" and args.if_stale and not stale:
        if not args.quiet:
            print("fresh, skipping rebuild")
        return 0

    files = scan_files(root)
    if langs is not None:
        files = [f for f in files if detect_language(f) in langs]
    missing = _missing_parser_langs(files)
    if missing:
        _bootstrap_or_die(missing, argv if argv is not None else sys.argv[1:])

    if args.cmd == "diff":
        with tempfile.TemporaryDirectory(prefix="hologram-diff-") as tmp:
            wt = Path(tmp) / "wt"
            r = subprocess.run(
                ["git", "-C", str(root), "worktree", "add", "--detach", "-f",
                 str(wt), args.rev],
                capture_output=True, text=True)
            if r.returncode != 0:
                raise SystemExit(f"git worktree failed: {r.stderr.strip()}")
            try:
                old = build_digest(wt, langs=langs)
                new = build_digest(root, langs=langs)
            finally:
                subprocess.run(["git", "-C", str(root), "worktree", "remove",
                                "--force", str(wt)], capture_output=True)
        body_old = old.splitlines()[2:]  # drop state-bearing header + notation line
        body_new = new.splitlines()[2:]
        for ln in difflib.unified_diff(body_old, body_new, fromfile=args.rev,
                                       tofile="worktree", lineterm=""):
            print(ln)
        return 0

    if args.cmd == "print":
        digest = build_digest(root, langs=langs)
        _warn_if_large(digest, args.warn_tokens)
        print(digest, end="")
        return 0

    if args.cmd == "init":
        _install_hooks(root, args.quiet, langs)
    for script in sorted(_dead_hook_scripts(root)):
        print(f"hologram: warning: a git hook still points at {script}, which no "
              f"longer exists — run `hologram init --root {root}` to repair it",
              file=sys.stderr)
    digest = build_digest(root, langs=langs)
    _warn_if_large(digest, args.warn_tokens)
    for t in targets:
        embed_digest(t, digest)
    if not args.quiet:
        names = ", ".join(str(t.relative_to(root)) for t in targets)
        print(f"hologram: {estimate_tokens(digest)} tokens embedded in {names}")
    return 0



def main() -> None:
    raise SystemExit(run_cli())
